commit

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -213,5 +213,40 @@ pipeline {
                 }
             }
         }
+
+        stage('Run Ansible Playbook') {
+            steps {
+                script {
+                    dir('ansible') {
+                        sh """
+                        if [ -f "docker_deploy_playbook.yml" ]; then
+                            echo "Found playbook docker_deploy_playbook.yml"
+
+                            # Ensure community.docker collection is installed
+                            ansible-galaxy collection install community.docker --force
+                            # Run the Ansible playbook
+                            ansible-playbook -i hosts docker_deploy_playbook.yml
+                        else
+                            echo "Playbook docker_deploy_playbook.yml not found!"
+                            exit 1
+                        fi
+                        """
+                    }
+                }
+            }
+        }
+    }
+
+    post {
+        success {
+            script {
+                def instanceUrl = "http://${EC2_PUBLIC_IP}:81"
+                echo "The instance is successfully deployed. Access it here:
+                ${instanceUrl}"
+            }
+        }
+        failure {
+            echo "The pipeline failed. Please check the logs for details."
+        }
     }
 }
